<?php

return [
    [
        'title' => 'test title 1',
        'description' => '1. ',
        'cost' => 249,
        'discountCost' => 199,
        'new' => true,
        'img'  => '/img/img_product.png',
    ],
    [
        'title' => 'test title 2',
        'description' => '2 when looking at its layout. ',
        'cost' => 249,
        'discountCost' => null,
        'new' => false,
        'img'  => '/img/img_product.png',
    ],
    [
        'title' => 'test title 3',
        'description' => '3 It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 125,
        'new' => true,
        'discountCost' => null,
        'img'  => '/img/img_product.png',
    ],
    [
        'title' => 'test title 4',
        'description' => '4 It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 111,
        'discountCost' => 90,
        'new' => false,
        'img'  => '/img/img_product.png',
    ],
    [
        'title' => 'test title 5',
        'description' => '5 It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 249,
        'discountCost' => null,
        'new' => true,
        'img'  => '/img/img_product.png',
    ],
    [
        'title' => 'test title 6',
        'description' => '6 It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 249,
        'discountCost' => null,
        'new' => true,
        'img'  => '/img/img_product.png',
    ],
    [
        'title' => 'test title 7',
        'description' => '7 It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 249,
        'discountCost' => null,
        'new' => false,
        'img'  => '/img/img_product.png',
    ],
    [
        'title' => 'test title 8',
        'description' => '8 It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 249,
        'discountCost' => null,
        'new' => false,
        'img'  => '/img/img_product.png',
    ],
    [
        'title' => 'test title 9',
        'description' => '9 ',
        'cost' => 249,
        'discountCost' => 10,
        'new' => false,
        'img'  => '/img/img_product.png',
    ],
    [
        'title' => 'test title 10',
        'description' => '10 ',
        'cost' => 249,
        'discountCost' => 100,
        'new' => false,
        'img'  => '/img/img_product.png',
    ],
    [
        'title' => 'test title 11',
        'description' => '11 ',
        'cost' => 259,
        'discountCost' => 100,
        'new' => false,
        'img'  => '/img/img_product.png',
    ],
    [
        'title' => 'test title 12',
        'description' => '12 ',
        'cost' => 245,
        'discountCost' => 150,
        'new' => false,
        'img'  => '/img/img_product.png',
    ],
    [
        'title' => 'test title 13',
        'description' => '13 ',
        'cost' => 29,
        'discountCost' => 10,
        'new' => false,
        'img'  => '/img/img_product.png',
    ],
    [
        'title' => 'test title 14',
        'description' => '14 ',
        'cost' => 249,
        'discountCost' => 100,
        'new' => false,
        'img'  => '/img/img_product.png',
    ],
    [
        'title' => 'test title 15',
        'description' => '15 ',
        'cost' => 249,
        'discountCost' => 10,
        'new' => false,
        'img'  => '/img/img_product.png',
    ],
    [
        'title' => 'test title 16',
        'description' => '16 ',
        'cost' => 249,
        'discountCost' => 100,
        'new' => false,
        'img'  => '/img/img_product.png',
    ],
    [
        'title' => 'test title 17',
        'description' => '17 ',
        'cost' => 249,
        'discountCost' => 100,
        'new' => false,
        'img'  => '/img/img_product.png',
    ],
    [
        'title' => 'test title 18',
        'description' => '18 ',
        'cost' => 249,
        'discountCost' => 100,
        'new' => false,
        'img'  => '/img/img_product.png',
    ],
    [
        'title' => 'test title 19',
        'description' => '19 ',
        'cost' => 259,
        'discountCost' => 100,
        'new' => false,
        'img'  => '/img/img_product.png',
    ],
    [
        'title' => 'test title 20',
        'description' => '20 ',
        'cost' => 245,
        'discountCost' => 150,
        'new' => false,
        'img'  => '/img/img_product.png',
    ],
    [
        'title' => 'test title 21',
        'description' => '21 ',
        'cost' => 29,
        'discountCost' => 10,
        'new' => false,
        'img'  => '/img/img_product.png',
    ],
    [
        'title' => 'test title 22',
        'description' => '22 ',
        'cost' => 249,
        'discountCost' => 100,
        'new' => false,
        'img'  => '/img/img_product.png',
    ],
    [
        'title' => 'test title 23',
        'description' => '23 ',
        'cost' => 249,
        'discountCost' => 10,
        'new' => false,
        'img'  => '/img/img_product.png',
    ],
    [
        'title' => 'test title 24',
        'description' => '24 ',
        'cost' => 249,
        'discountCost' => 100,
        'new' => false,
        'img'  => '/img/img_product.png',
    ],
    [
        'title' => 'test title 25',
        'description' => '25 ',
        'cost' => 249,
        'discountCost' => 100,
        'new' => false,
        'img'  => '/img/img_product.png',
    ],
];